import React from 'react';
import { Link } from 'react-router-dom';

const features = [
  { icon: '🗓️', title: 'AI Study Plans', desc: 'Personalized day-by-day schedules generated by IBM watsonx.ai based on your exam date and study hours.' },
  { icon: '🔍', title: 'Topic Explainer', desc: 'Get clear explanations for any topic at your level — beginner, intermediate, or advanced.' },
  { icon: '✏️', title: 'Smart Quizzes', desc: 'AI-generated quizzes detect your weak areas and guide focused revision.' },
  { icon: '📊', title: 'Progress Tracking', desc: 'Visual dashboards show your learning progress, quiz scores, and study streaks.' },
  { icon: '🤖', title: 'AI Study Assistant', desc: 'Ask anything — "What should I study today?" or "Explain recursion simply."' },
  { icon: '🎯', title: 'Weak Topic Detection', desc: 'Automatically identifies your weakest topics and recommends targeted study sessions.' }
];

const subjects = ['Python 🐍', 'Data Structures 🌲', 'Computer Networks 🌐', 'Database Management 🗄️', 'Artificial Intelligence 🤖'];

const Landing = () => (
  <div style={{ minHeight: '100vh', background: '#ffffff' }}>
    {/* Nav */}
    <nav style={{ padding: '0 40px', height: 60, display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid #e0e0e0', background: '#ffffff', position: 'sticky', top: 0, zIndex: 10 }}>
      <div style={{ fontWeight: 700, fontSize: '1.1rem', color: '#161616' }}>
        <span style={{ color: '#0f62fe' }}>IBM</span> StudyMate
      </div>
      <div style={{ display: 'flex', gap: 12 }}>
        <Link to="/login" className="btn btn-secondary btn-sm">Sign In</Link>
        <Link to="/register" className="btn btn-primary btn-sm">Get Started</Link>
      </div>
    </nav>

    {/* Hero */}
    <div style={{ background: 'linear-gradient(135deg, #0f62fe 0%, #0043ce 100%)', color: '#ffffff', padding: '80px 40px', textAlign: 'center' }}>
      <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, background: 'rgba(255,255,255,0.15)', padding: '4px 14px', borderRadius: 20, fontSize: '0.8125rem', marginBottom: 20, backdropFilter: 'blur(4px)' }}>
        ⚡ Powered by IBM watsonx.ai
      </div>
      <h1 style={{ fontSize: 'clamp(2rem, 5vw, 3.5rem)', fontWeight: 700, lineHeight: 1.1, marginBottom: 20, maxWidth: 700, margin: '0 auto 20px' }}>
        Your AI-Powered Personalized Learning Platform
      </h1>
      <p style={{ fontSize: '1.125rem', opacity: 0.85, maxWidth: 560, margin: '0 auto 36px', lineHeight: 1.6 }}>
        IBM StudyMate analyzes your learning goals, exam schedule, and knowledge gaps to build a perfect study plan — just for you.
      </p>
      <div style={{ display: 'flex', gap: 14, justifyContent: 'center', flexWrap: 'wrap' }}>
        <Link to="/register" className="btn btn-lg" style={{ background: '#ffffff', color: '#0f62fe', fontWeight: 600 }}>
          Start Learning Free →
        </Link>
        <Link to="/login" className="btn btn-lg" style={{ background: 'rgba(255,255,255,0.15)', color: '#ffffff', border: '2px solid rgba(255,255,255,0.4)' }}>
          Sign In
        </Link>
      </div>
    </div>

    {/* Subjects strip */}
    <div style={{ background: '#f4f4f4', padding: '16px 40px', display: 'flex', gap: 12, flexWrap: 'wrap', justifyContent: 'center', alignItems: 'center' }}>
      <span style={{ fontSize: '0.8125rem', color: '#525252', fontWeight: 600 }}>Subjects covered:</span>
      {subjects.map(s => (
        <span key={s} className="badge badge-blue" style={{ fontSize: '0.8rem' }}>{s}</span>
      ))}
    </div>

    {/* Features */}
    <div style={{ padding: '64px 40px', maxWidth: 1100, margin: '0 auto' }}>
      <h2 style={{ textAlign: 'center', fontSize: '2rem', fontWeight: 700, marginBottom: 8, color: '#161616' }}>Everything you need to ace your exams</h2>
      <p style={{ textAlign: 'center', color: '#525252', marginBottom: 48 }}>Built with IBM AI technology for real students</p>
      <div className="grid grid-3">
        {features.map(f => (
          <div key={f.title} className="card" style={{ textAlign: 'center', padding: 28 }}>
            <div style={{ fontSize: '2.5rem', marginBottom: 14 }}>{f.icon}</div>
            <h3 style={{ fontWeight: 600, marginBottom: 8 }}>{f.title}</h3>
            <p style={{ color: '#525252', fontSize: '0.875rem', lineHeight: 1.6 }}>{f.desc}</p>
          </div>
        ))}
      </div>
    </div>

    {/* CTA */}
    <div style={{ background: '#161616', color: '#ffffff', padding: '64px 40px', textAlign: 'center' }}>
      <h2 style={{ fontSize: '2rem', fontWeight: 700, marginBottom: 12 }}>Ready to study smarter?</h2>
      <p style={{ opacity: 0.7, marginBottom: 28 }}>Join students using IBM AI to prepare better for their exams.</p>
      <Link to="/register" className="btn btn-primary btn-lg">Create Your Free Account →</Link>
      <div style={{ marginTop: 32, fontSize: '0.8125rem', color: '#8d8d8d' }}>
        IBM StudyMate is a student project demonstrating IBM watsonx.ai integration. <br />Not an official IBM product.
      </div>
    </div>
  </div>
);

export default Landing;
